In [18]:
import network
import csv
import numpy as np    
import pandas as pd
import random
import tensorflow as tf


In [19]:
# default_list = []

# with open("Test/Data/ccdefault.csv") as csvfile:
#     default_data = csv.reader(csvfile,delimiter = ",")
#     for row in default_data:
# #         print(row)
#         default_list.append(row)

In [20]:
# print(default_list)
default_data_pdf = pd.DataFrame.from_csv("Test/Data/ccdefault.csv")
# default_data_pdf
# feature_list = ['LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_0', 'PAY_2',
#        'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2',
#        'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1',
#        'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6']

# to customise the feature list
feature_list = ['LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_0', 'PAY_2',
       'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2',
       'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1',
       'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6']

feature_list = ['SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_0', 'PAY_2',
       'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2',
       'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1',
       'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6']
# default_data_pdf.shape

feature_num = len(feature_list)

# to split the data set to training and test set


In [21]:
training_set_size = 25000
test_set_size = default_data_pdf.shape[0] -training_set_size

feature_pdf = default_data_pdf.loc[:, feature_list]
label_pdf = default_data_pdf.loc[:, ["DEFAULT"]]
print(feature_pdf.shape,label_pdf.shape)
training_pdf = feature_pdf.iloc[0:training_set_size, ]
training_label_pdf = label_pdf.iloc[0:training_set_size, ]
 
test_pdf = feature_pdf.iloc[training_set_size: ,]
test_label_pdf = label_pdf.iloc[training_set_size:, ]


# training_data_array = training_pdf.values
input_x = np.array([x  for x in training_pdf.values]).astype(np.int)
# get a vector [default, not default]
label_y = np.array([[x[0], 1 -int( x[0] )] for x in training_label_pdf.values]).astype(np.int)



test_input_x = np.array([x  for x in test_pdf.values]).astype(np.int)
# get a vector [default, not default]
test_label_y = np.array([[x[0], 1 -int( x[0] )] for x in test_label_pdf.values]).astype(np.int)





(30000, 22) (30000, 1)


In [22]:
# label_y.shape

In [23]:
# print(label_y)
def get_batch(num):
    batch_indx = np.random.randint(0,feature_num, num)
    
    x_batch = [input_x[x] for x in batch_indx]
    y_batch = [label_y[x] for x in batch_indx]
    
    return x_batch,y_batch
def batch_generator(batch_sz):
    length = input_x.size
    
    index_array = np.arange(length)
    random.shuffle(index_array)
    counter = 0
    
    while counter  < length:
        yield input_x[counter: counter + batch_sz],label_y[counter: counter + batch_sz]
        counter += batch_sz
        

In [24]:
# print(len(default_list[0]))
# len(label_y[0])

In [25]:
# feature_num = len(default_list[0])-2
x = tf.placeholder(tf.float32,[None, feature_num])
W = tf.Variable(tf.zeros([feature_num,2]))
b = tf.Variable(tf.zeros([2]))

In [26]:
y = tf.nn.softmax(tf.matmul(x,W)+b)
y_ = tf.placeholder(tf.float32,[None,2])


In [ ]:
cross_entropy = tf.reduce_mean(
      tf.nn.softmax_cross_entropy_with_logits(labels=y_, logits=y))
train_step = tf.train.GradientDescentOptimizer(0.5).minimize(cross_entropy)

sess = tf.InteractiveSession()
tf.global_variables_initializer().run()


  # Train
epoch = 2
batch_size = 100
print("there epoch: {}, and batch size: {}".format(epoch,batch_size))
for e in range(epoch):
    print("epoch: {}...".format(e))
    for batch in batch_generator(batch_size):
        sess.run(train_step, feed_dict={x: batch[0], y_: batch[1]})
    correct_prediction = tf.equal(tf.argmax(y, 1), tf.argmax(y_, 1))
    accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
    print("\tinput dataset accuracy: {}".format(sess.run(accuracy,feed_dict={x: input_x,y_:label_y})))
    print("\ttest  dataset accuracy: {}".format(sess.run(accuracy,feed_dict={x: test_input_x,y_:test_label_y})))
          
    
    


there epoch: 2, and batch size: 100
epoch: 0...


In [102]:
# print(default_list[1])

In [143]:
correct_prediction = tf.equal(tf.argmax(y, 1), tf.argmax(y_, 1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

In [144]:
print(sess.run(accuracy,feed_dict={x: input_x,y_:label_y}))

0.77432


In [145]:
print(sess.run(accuracy,feed_dict={x: test_input_x,y_:test_label_y}))

0.7848


In [5]:
range(0,100)

range(0, 100)

In [6]:
np.arange(10,100)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [7]:
def batch_generator(batch_sz):
    length = input_x.size
    
    index_array = np.arrange(length)
    random.shuffle(index_array)
    counter = 0
    
    while counter  < length:
        yield input_x[counter: counter + batch_sz],label[counter: counter + batch_sz]
        counter += batch_sz
        
        

In [19]:
input_x.shape

(25000, 22)

In [21]:
a = np.arange(10)

In [23]:
random.shuffle(a)

In [24]:
a

array([5, 4, 7, 1, 8, 2, 3, 9, 0, 6])

In [31]:
a = np.arange(10)
print(a)
random.shuffle(a)
print(a)

[0 1 2 3 4 5 6 7 8 9]
[2 7 6 1 4 0 8 5 9 3]


In [26]:
a

array([3, 4, 1, 9, 5, 0, 8, 2, 6, 7])